<?php

namespace Modules\Category\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Category\Models\Category;

class CategoryDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $defaultCategories = ([
            [
                'title' => 'پیراهن',
                'slug' => 'پیراهن',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'مجموعه‌ای از پیراهن‌های مردانه و زنانه با طرح‌ها و رنگ‌های متنوع.',
                'parent_id' => null,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'shirts-category.jpg',
            ],
            [
                'title' => 'شلوار',
                'slug' => 'شلوار',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'انواع شلوارهای جین، کتان و رسمی برای آقایان و خانم‌ها.',
                'parent_id' => null,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'pants-category.jpg',
            ],
            [
                'title' => 'کفش',
                'slug' => 'کفش',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'کفش‌های اسپرت، رسمی و بوت‌های زمستانی مناسب برای همه فصل‌ها.',
                'parent_id' => null,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'shoes-category.jpg',
            ],
            [
                'title' => 'لباس‌های ورزشی',
                'slug' => 'لباس-های-ورزشی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'انواع لباس‌های ورزشی مناسب برای تمرین و باشگاه.',
                'parent_id' => null,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'sportswear-category.jpg',
            ],
            [
                'title' => 'اکسسوری',
                'slug' => 'اکسسوری',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'اکسسوری‌های مردانه و زنانه شامل کمربند، کیف و کلاه.',
                'parent_id' => null,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'accessories-category.jpg',
            ],
            [
            'title' => 'لباس کودک',
            'slug' => 'لباس-کودک',
            'status' => Category::ACTIVE_STATUS,
            'description' => 'لباس‌های کودکانه با طرح‌های جذاب و رنگارنگ.',
            'parent_id' => null,
            'type' => Category::PRODUCT_TYPE,
            'img' => 'kids-clothing-category.jpg',
            ],
            [
                'title' => 'لباس‌های تابستانی',
                'slug' => 'لباس-های-تابستانی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'مجموعه‌ای از لباس‌های تابستانی سبک و خنک برای روزهای گرم.',
                'parent_id' => null,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'summer-clothing-category.jpg',
            ],
            [
                'title' => 'لباس‌های زمستانی',
                'slug' => 'لباس-های-زمستانی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'پوشاک زمستانی گرم شامل کاپشن، پالتو و ژاکت.',
                'parent_id' => null,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'winter-clothing-category.jpg',
            ],
            [
                'title' => 'لباس رسمی',
                'slug' => 'لباس-رسمی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'مجموعه‌ای از لباس‌های رسمی و مجلسی برای مناسبت‌های خاص.',
                'parent_id' => null,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'formal-clothing-category.jpg',
            ],
            [
                'title' => 'زیورآلات',
                'slug' => 'زیورآلات',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'زیورآلات شامل گردنبند، دستبند و گوشواره.',
                'parent_id' => null,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'jewelry-category.jpg',
            ],
            [
                'title' => 'پیراهن مردانه',
                'slug' => 'پیراهن-مردانه',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'مجموعه‌ای از پیراهن‌های مردانه با طرح‌های رسمی و روزمره.',
                'parent_id' => 1,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'mens-shirts.jpg',
            ],
            [
                'title' => 'پیراهن زنانه',
                'slug' => 'پیراهن-زنانه',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'پیراهن‌های زنانه در طرح‌های متنوع و شیک.',
                'parent_id' => 1,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'womens-shirts.jpg',
            ],
            [
                'title' => 'شلوار جین',
                'slug' => 'شلوار-جین',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'شلوارهای جین متناسب با استایل‌های مختلف.',
                'parent_id' => 2,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'jeans.jpg',
            ],
            [
                'title' => 'شلوار کتان',
                'slug' => 'شلوار-کتان',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'شلوارهای کتان راحت و مناسب برای استفاده روزانه.',
                'parent_id' => 2,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'cotton-pants.jpg',
            ],
            [
                'title' => 'کفش اسپرت',
                'slug' => 'کفش-اسپرت',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'کفش‌های اسپرت مناسب برای ورزش و پیاده‌روی.',
                'parent_id' => 3,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'sport-shoes.jpg',
            ],
            [
                'title' => 'بوت زمستانی',
                'slug' => 'بوت-زمستانی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'بوت‌های گرم و مقاوم برای روزهای سرد زمستان.',
                'parent_id' => 3,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'winter-boots.jpg',
            ],
            [
                'title' => 'لباس ورزشی مردانه',
                'slug' => 'لباس-ورزشی-مردانه',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'لباس‌های ورزشی مخصوص آقایان برای تمرینات ورزشی.',
                'parent_id' => 4,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'mens-sportswear.jpg',
            ],
            [
                'title' => 'لباس ورزشی زنانه',
                'slug' => 'لباس-ورزشی-زنانه',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'لباس‌های ورزشی زنانه مناسب برای تمرین و ورزش.',
                'parent_id' => 4,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'womens-sportswear.jpg',
            ],
            [
                'title' => 'کمربند چرم',
                'slug' => 'کمربند-چرم',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'کمربندهای چرمی با کیفیت بالا برای استایل رسمی.',
                'parent_id' => 5,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'leather-belt.jpg',
            ],
            [
                'title' => 'کیف دستی زنانه',
                'slug' => 'کیف-دستی-زنانه',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'کیف‌های دستی شیک و مدرن مخصوص خانم‌ها.',
                'parent_id' => 5,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'womens-handbag.jpg',
            ],
            [
                'title' => 'کفش رسمی',
                'slug' => 'کفش-رسمی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'کفش‌های رسمی مناسب برای محل کار و مجالس.',
                'parent_id' => 3,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'formal-shoes.jpg',
            ],
            [
                'title' => 'کلاه',
                'slug' => 'کلاه',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'مجموعه‌ای از کلاه‌های فصلی و ورزشی برای استایل‌های مختلف.',
                'parent_id' => 5,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'hats.jpg',
            ],
            [
                'title' => 'کاپشن',
                'slug' => 'کاپشن',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'کاپشن‌های گرم و راحت برای روزهای سرد زمستانی.',
                'parent_id' => 8,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'jackets.jpg',
            ],
            [
                'title' => 'زیورآلات نقره',
                'slug' => 'زیورآلات-نقره',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'زیورآلات ساخته شده از نقره با طرح‌های خاص و جذاب.',
                'parent_id' => 10,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'silver-jewelry.jpg',
            ],
            [
                'title' => 'لباس‌های ساحلی',
                'slug' => 'لباس-های-ساحلی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'لباس‌های مناسب برای استفاده در کنار ساحل و استخر.',
                'parent_id' => 7,
                'type' => Category::PRODUCT_TYPE,
                'img' => 'beachwear.jpg',
            ],

            // blog

            [
                'title' => 'تکنولوژی',
                'slug' => 'تکنولوژی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'اخبار و مقالات مربوط به آخرین دستاوردها و نوآوری‌های دنیای تکنولوژی.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'technology-blog.jpg',
            ],
            [
                'title' => 'سلامت و بهداشت',
                'slug' => 'سلامت-و-بهداشت',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'نکات و توصیه‌های مربوط به سلامت جسمی و روانی و مراقبت‌های بهداشتی.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'health-blog.jpg',
            ],
            [
                'title' => 'سبک زندگی',
                'slug' => 'سبک-زندگی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'مطالب و مقالاتی در مورد سبک زندگی مدرن و بهتر زیستن.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'lifestyle-blog.jpg',
            ],
            [
                'title' => 'سفر و گردشگری',
                'slug' => 'سفر-و-گردشگری',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'راهنمایی‌ها و داستان‌های سفر به نقاط دیدنی جهان.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'travel-blog.jpg',
            ],
            [
                'title' => 'توسعه فردی',
                'slug' => 'توسعه-فردی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'مقالات آموزشی برای رشد فردی، افزایش بهره‌وری و موفقیت شخصی.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'personal-development-blog.jpg',
            ],
            [
                'title' => 'آشپزی و غذا',
                'slug' => 'آشپزی-و-غذا',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'دستور پخت انواع غذاها، شیرینی‌ها و نکات مربوط به آشپزی.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'cooking-blog.jpg',
            ],
            [
                'title' => 'سرمایه‌گذاری و امور مالی',
                'slug' => 'سرمایه-گذاری-و-امور-مالی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'نکات و راهنمایی‌هایی برای مدیریت مالی و سرمایه‌گذاری.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'finance-blog.jpg',
            ],
            [
                'title' => 'مد و زیبایی',
                'slug' => 'مد-و-زیبایی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'اخبار و مقالات مربوط به جدیدترین ترندهای مد و زیبایی.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'fashion-blog.jpg',
            ],
            [
                'title' => 'ورزش و تناسب اندام',
                'slug' => 'ورزش-و-تناسب-اندام',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'نکات و برنامه‌های ورزشی برای داشتن بدنی سالم و متناسب.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'fitness-blog.jpg',
            ],
            [
                'title' => 'اخبار فرهنگی و هنری',
                'slug' => 'اخبار-فرهنگی-و-هنری',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'مطالب و مقالات مرتبط با هنر، فرهنگ و رویدادهای فرهنگی.',
                'parent_id' => null,
                'type' => Category::BLOG_TYPE,
                'img' => 'culture-art-blog.jpg',
            ],
            [
                'title' => 'گجت‌های جدید',
                'slug' => 'گجت-های-جدید',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'بررسی و معرفی جدیدترین گجت‌ها و ابزارهای الکترونیکی.',
                'parent_id' => 1,
                'type' => Category::BLOG_TYPE,
                'img' => 'gadgets-blog.jpg',
            ],
            [
                'title' => 'سلامت روان',
                'slug' => 'سلامت-روان',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'نکات و توصیه‌های مربوط به بهبود سلامت روان.',
                'parent_id' => 2,
                'type' => Category::BLOG_TYPE,
                'img' => 'mental-health-blog.jpg',
            ],
            [
                'title' => 'دکوراسیون داخلی',
                'slug' => 'دکوراسیون-داخلی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'ایده‌های جذاب برای دکوراسیون داخلی منزل و محل کار.',
                'parent_id' => 3,
                'type' => Category::BLOG_TYPE,
                'img' => 'interior-design-blog.jpg',
            ],
            [
                'title' => 'مقاصد گردشگری',
                'slug' => 'مقاصد-گردشگری',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'معرفی مکان‌های دیدنی و مقاصد گردشگری جذاب.',
                'parent_id' => 4,
                'type' => Category::BLOG_TYPE,
                'img' => 'tourist-destinations-blog.jpg',
            ],
            [
                'title' => 'مدیریت زمان',
                'slug' => 'مدیریت-زمان',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'نکات و تکنیک‌های موثر برای مدیریت زمان بهتر.',
                'parent_id' => 5,
                'type' => Category::BLOG_TYPE,
                'img' => 'time-management-blog.jpg',
            ],
            [
                'title' => 'غذاهای سنتی',
                'slug' => 'غذاهای-سنتی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'دستور پخت غذاهای سنتی و محلی ایرانی و بین‌المللی.',
                'parent_id' => 6,
                'type' => Category::BLOG_TYPE,
                'img' => 'traditional-food-blog.jpg',
            ],
            [
                'title' => 'ارزهای دیجیتال',
                'slug' => 'ارزهای-دیجیتال',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'اطلاعات و تحلیل‌های مربوط به بیت‌کوین و دیگر ارزهای دیجیتال.',
                'parent_id' => 7,
                'type' => Category::BLOG_TYPE,
                'img' => 'cryptocurrency-blog.jpg',
            ],
            [
                'title' => 'آرایش و زیبایی',
                'slug' => 'آرایش-و-زیبایی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'تکنیک‌ها و توصیه‌هایی برای آرایش و مراقبت از پوست و مو.',
                'parent_id' => 8,
                'type' => Category::BLOG_TYPE,
                'img' => 'beauty-tips-blog.jpg',
            ],
            [
                'title' => 'تمرینات خانگی',
                'slug' => 'تمرینات-خانگی',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'برنامه‌های ورزشی برای انجام تمرینات در خانه بدون تجهیزات.',
                'parent_id' => 9,
                'type' => Category::BLOG_TYPE,
                'img' => 'home-workout-blog.jpg',
            ],
            [
                'title' => 'نقد فیلم',
                'slug' => 'نقد-فیلم',
                'status' => Category::ACTIVE_STATUS,
                'description' => 'بررسی و نقد فیلم‌های جدید و محبوب در دنیای سینما.',
                'parent_id' => 10,
                'type' => Category::BLOG_TYPE,
                'img' => 'movie-reviews-blog.jpg',
            ],

        ]);

        foreach ($defaultCategories as $category)
            Category::firstOrCreate($category);
    }
}
